"use client";

import { useParams, useRouter } from "next/navigation";
import { useMutation, useQuery } from "convex/react";
import { format } from "date-fns";
import { CalendarDays, CheckCircle, Clock, FileUser, Save, SendHorizontal, XCircle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { FaMapMarkerAlt } from "react-icons/fa";
import AdminPanelLayout from "@/components/admin-panel/admin-panel-layout";
import { ContentLayout } from "@/components/admin-panel/content-layout";
import { api } from "../../../../../convex/_generated/api";
import { Id } from "../../../../../convex/_generated/dataModel";
import { Label } from "@/components/ui/label";
import BlockEditor from "@/components/BlockEditor";
import { Skeleton } from "@/components/ui/skeleton";
import { Spinner } from "@/components/spinner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { useEffect, useState } from "react";
import { useToast } from "@/hooks/use-toast";

export default function JobDetailsPage() {
  const params = useParams();
  const jobId = params.id as Id<"jobs">;
  const job = useQuery(api.queries.jobs.getJobById, { id: jobId });
  const Me = useQuery(api.auth.getMe);
  const createOffer = useMutation(api.mutations.offers.createOffer);
  const router = useRouter();

  useEffect(() => {
    if (Me && Me.department?.name !== null) {
      router.push("/access-denied");
    }
  }, [Me, router]);
  const isLoading = job === undefined;

  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [coverLetter, setCoverLetter] = useState("");
  const [resume, setResume] = useState<File | null>(null);
  const [error, setError] = useState("");
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [extractedText, setExtractedText] = useState("");

  const existingApplication = useQuery(api.queries.offres.getOfferByCandidateAndJob, {
    candidateId: Me?._id as Id<"users">,
    jobId: jobId,
  });

  const getReportFromGemini = async (cvText: string, jobTitle: string, jobDetails: string): Promise<{ score: number; reportHtml: string }> => {
    try {
      // Template HTML avec des placeholders
      const templateHtml = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>CV Report</title>
          <style>
            /* Insérez ici le CSS du modèle */
          </style>
        </head>
        <body>
          <div class="report">
            <div class="header">
              <h1>CV Report for Job: {{jobTitle}}</h1>
              <div class="score">Score: {{score}}/100</div>
            </div>
            <div class="section">
              <h2>Analysis</h2>
              <p>{{analysis}}</p>
            </div>
            <div class="section">
              <h2>Job Details</h2>
              <p><strong>Title:</strong> {{jobTitle}}</p>
              <p><strong>Department:</strong> {{department}}</p>
              <p><strong>Requirements:</strong> {{requirements}}</p>
              <p><strong>Salary Range:</strong> {{salaryRange}}</p>
              <p><strong>Location:</strong> {{location}}</p>
              <p><strong>Employment Type:</strong> {{employmentType}}</p>
              <p><strong>Experience Level:</strong> {{experienceLevel}}</p>
            </div>
            <div class="footer">
              <p>Generated by Gemini AI</p>
            </div>
          </div>
        </body>
        </html>
      `;
  
      // Envoyer la requête à l'API Gemini
      const response = await fetch(
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=AIzaSyBX_Yq9iRL7hqCEwpZeUP4zepSaEk33yag",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: `Generate a detailed HTML report for the CV below applied to the job title "${jobTitle}". Use the following template and fill in the placeholders with relevant data:
  
                    Template:
                    ${templateHtml}
  
                    CV:
                    ${cvText}
  
                    Job Details:
                    ${jobDetails}`,
                  },
                ],
              },
            ],
          }),
        }
      );
  
      if (!response.ok) {
        throw new Error("Failed to fetch report from Gemini API.");
      }
  
      const data = await response.json();
      const reportHtml = data.candidates[0].content.parts[0].text;
  
      // Extraire le score du rapport HTML
      const scoreMatch = reportHtml.match(/Score: (\d+)/);
      const score = scoreMatch ? parseInt(scoreMatch[1], 10) : 0;
  
      return { score, reportHtml };
    } catch (error) {
      console.error("Error fetching report from Gemini:", error);
      throw new Error("Failed to fetch report from Gemini.");
    }
  };

  /**
   * Convertit le rapport HTML en PDF et le sauvegarde dans le dossier `upload`.
   */
  const saveHtmlAsPdf = async (html: string, fileName: string): Promise<string> => {
    try {
      const response = await fetch("/api/generate-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ html, fileName }), // Envoyer `fileName` dans la requête
      });
  
      if (!response.ok) {
        throw new Error("Failed to generate PDF.");
      }
  
      // Convertir la réponse en Blob
      const pdfBlob = await response.blob();
      const pdfUrl = URL.createObjectURL(pdfBlob);
  
      // Télécharger le PDF
      const link = document.createElement("a");
      link.href = pdfUrl;
      link.download = `${fileName}.pdf`;
  
      return pdfUrl;
    } catch (error) {
      console.error("Error generating PDF:", error);
      throw error;
    }
  };

  /**
   * Gère la soumission du formulaire de candidature.
   */
  const handleSubmit = async () => {
    if (existingApplication) {
      setError("You have already applied to this job.");
      return;
    }

    if (!resume) {
      setError("Please upload your resume.");
      return;
    }

    if (!Me) {
      setError("You must be logged in to apply.");
      return;
    }

    if (!job) {
      setError("Job details are not available.");
      return;
    }

    try {
      setIsSubmitting(true);

      // Étape 1 : Téléverser le CV
      const formData = new FormData();
      formData.append("file", resume);

      const uploadResponse = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });

      if (!uploadResponse.ok) {
        throw new Error("Failed to upload the file.");
      }

      const uploadData = await uploadResponse.json();
      const fileName = uploadData.fileName;

      // Étape 2 : Extraire le texte du CV
      const extractResponse = await fetch("/api/extract-text", {
        method: "POST",
        body: formData,
      });

      if (!extractResponse.ok) {
        throw new Error("Failed to extract text from the CV.");
      }

      const extractData = await extractResponse.json();
      const cvText = extractData.text;
      setExtractedText(cvText);

      // Étape 3 : Générer le rapport HTML avec Gemini
      const jobDetails = `
        Title: ${job.title}
        Department: ${job.departmentName}
        Requirements: ${job.requirements}
        Salary Range: ${job.salaryRange}
        Location: ${job.location}
        Employment Type: ${job.employmentType}
        Experience Level: ${job.experienceLevel}
      `;

      const { score, reportHtml } = await getReportFromGemini(cvText, job.title, jobDetails);
      console.log({ score, reportHtml } )

      const pdfFileName = `report_${Date.now()}`;
      const pdfFilePath = await saveHtmlAsPdf(reportHtml, pdfFileName);

      await createOffer({
        jobId: jobId as Id<"jobs">,
        candidateId: Me._id as Id<"users">,
        coverLetter: coverLetter,
        resume: fileName,
        status: "Pending",
        appliedAt: Date.now(),
        score: score,
        reportPdf: pdfFileName+".pdf", // Ajouter le chemin du PDF
      });

      // Afficher un message de succès
      toast({
        title: "Application submitted successfully",
        description: "Your application has been recorded.",
      });

      // Fermer le dialogue
      setIsDialogOpen(false);

      // Réinitialiser le formulaire
      setCoverLetter("");
      setResume(null);
      setError("");
    } catch (error) {
      console.error("Error submitting the application:", error);
      setError("An error occurred while submitting the application.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!job) {
    return (
      <div className="flex justify-center items-center min-h-screen w-full">
        <Spinner variant="ring" size={40} className="text-primary" />
      </div>
    );
  }

  const statusIcons = {
    Pending: <Clock size={12} className="text-yellow-500 -ms-0.5" strokeWidth={2} aria-hidden="true" />,
    Open: <CheckCircle size={12} className="text-green-500 -ms-0.5" strokeWidth={2} aria-hidden="true" />,
    Closed: <XCircle size={12} className="text-red-500 -ms-0.5" strokeWidth={2} aria-hidden="true" />,
  };

  const icon = statusIcons[job.status];

  return (
    <AdminPanelLayout>
      <ContentLayout title="Job Details">
        <div className="flex items-center justify-between mb-4">
          <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">Job Details & Application</h1>

          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button className="flex items-center justify-center w-[160px] h-[40px] gap-2">
                <SendHorizontal size={18} />
                <span>Apply Now</span>
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl">
              <DialogHeader>
                <DialogTitle>Apply for {job.title}</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                {existingApplication && <p className="text-red-500">You have already applied to this job.</p>}
                {error && <p className="text-red-500">{error}</p>}
                <Label>Cover Letter</Label>
                <Textarea value={coverLetter} onChange={(e) => setCoverLetter(e.target.value)} placeholder="Write your cover letter..." />
                <Label>Upload Resume</Label>
                <Input type="file" accept="application/pdf" onChange={(e) => setResume(e.target.files?.[0] || null)} />
              </div>
              <DialogFooter>
                <Button onClick={() => setIsDialogOpen(false)}>Cancel</Button>
                <Button onClick={handleSubmit} disabled={isSubmitting || !!existingApplication}>
                  {isSubmitting ? "Submitting..." : "Submit Application"}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        <p className="leading-7 [&:not(:first-child)]:mb-6">View job details, requirements, and compensation. Submit your application to take the next step in your career.</p>

        {isLoading ? (
          <div className="flex justify-center items-center h-[300px] w-full">
            <Spinner variant="ring" size={40} className="text-primary" />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Left Panel */}
            <div className="space-y-6">
              {/* Job Details Section */}
              <div className="flex-1 flex flex-col">
                <h3 className="scroll-m-20 text-xl font-semibold tracking-tight">Job Details</h3>
                <p className="text-sm text-muted-foreground">Essential information about the job.</p>
              </div>
              <div className="space-y-4">
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Title</Label>
                  <p className="text-sm">{job.title}</p>
                </div>
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Department</Label>
                  <p className="text-sm">{job.departmentName}</p>
                </div>
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Requirements</Label>
                  <p className="text-sm">{job.requirements}</p>
                </div>
              </div>

              <Separator className="my-4" />

              {/* Compensation & Location Section */}
              <div className="flex-1 flex flex-col">
                <h3 className="scroll-m-20 text-xl font-semibold tracking-tight">Compensation & Location</h3>
                <p className="text-sm text-muted-foreground">Salary range and location.</p>
              </div>
              <div className="space-y-4">
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Salary Range</Label>
                  <p className="text-lg ml-2">{job.salaryRange} DT</p>
                  <p className="text-sm text-muted-foreground">
                    <span className="font-medium">/ Month</span>
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Location</Label>
                  <div className="flex items-center text-sm mb-1">
                    <FaMapMarkerAlt className="mr-2" />
                    <span>{job.location}</span>
                  </div>
                </div>
              </div>

              <Separator className="my-4" />

              {/* Employment Details Section */}
              <div className="flex-1 flex flex-col">
                <h3 className="scroll-m-20 text-xl font-semibold tracking-tight">Employment Details</h3>
                <p className="text-sm text-muted-foreground">Employment type, experience level, and tags.</p>
              </div>
              <div className="space-y-4">
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Employment Type</Label>
                  <p className="text-sm">{job.employmentType}</p>
                </div>
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Experience Level</Label>
                  <p className="text-sm">{job.experienceLevel}</p>
                </div>
                <div className="flex items-center gap-4">
                  <Label className="min-w-28 whitespace-nowrap font-bold">Tags</Label>
                  <div className="flex flex-wrap gap-2">
                    {job.tags?.map((tag, index) => (
                      <Badge key={index} variant="outline">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                </div>
              </div>

              <Separator className="my-4" />

              {/* Application & Interview Section */}
              <div className="flex-1 flex flex-col">
                <h3 className="scroll-m-20 text-xl font-semibold tracking-tight">Application & Interview</h3>
                <p className="text-sm text-muted-foreground">Application deadline and interview process.</p>
              </div>
              <div className="space-y-4">
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Application Deadline</Label>
                  <div className="flex items-center text-sm">
                    <CalendarDays className="mr-2" size={16} />
                    <span>{job.applicationDeadline ? format(new Date(job.applicationDeadline), "PPP") : "N/A"}</span>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <Label className="min-w-24 whitespace-nowrap font-bold">Interview Process</Label>
                  <p className="text-sm">{job.interviewProcess}</p>
                </div>
              </div>
            </div>

            {/* Right Panel */}
            <div className="space-y-6">
              {/* Description Section */}
              <Card className="p-6 h-full flex flex-col">
                <div className="flex-1 flex flex-col">
                  <h3 className="scroll-m-20 text-xl font-semibold tracking-tight">Job Description</h3>
                  <p className="text-sm text-muted-foreground">Detailed description of the job.</p>
                  <div className="flex-1 overflow-y-auto">
                    <BlockEditor initialContent={job.description} onChange={() => { }} editable={false} />
                  </div>
                </div>
              </Card>
            </div>
          </div>
        )}
      </ContentLayout>
    </AdminPanelLayout>
  );
}