sonar.projectKey=myprj
sonar.projectName=myprj
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_2df4290f6538a67efb315f3055a4e4cf3d242094
